name = 'Bitshares RPG'
description = 'A proof of concept RPG for the Bitshares and EOS blockchains!'

modules = [
    './main',
    '@rpgjs/mobile-gui',
    '@rpgjs/default-gui',
    '@rpgjs/gamepad'
]

[compilerOptions.alias]
  "@" = "./main"

[vite]
    assetsInclude = "**/*.html"

[start]
    map = 'map'
    hitbox = [16, 16]

[inputs.up]
    name = "up"
    repeat = true
    bind = ["up", "w"]

[inputs.down]
    name = "down"
    repeat = true
    bind = ["down", "s"]

[inputs.right]
    name = "right"
    repeat = true
    bind = ["right", "d"]

[inputs.left]
    name = "left"
    repeat = true
    bind = ["left", "a"]